### Editar un curso (POST)

# Simular POST con nuevos datos del curso

PUT http://localhost:5000/libros/4
Content-Type: application/json

{
  "titulo": "Libro actualizado",
  "descripcion": "Nueva descripción actualizada"
}
